# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=256, verbose_name='заголовок')),
                ('city', models.CharField(max_length=64, verbose_name='город')),
                ('price', models.CharField(max_length=64, verbose_name='цена')),
                ('position', models.IntegerField(verbose_name='позиция объявления')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='категория')),
            ],
        ),
        migrations.AddField(
            model_name='ads',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.Categories', verbose_name='категория'),
        ),
    ]
