# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='url',
            field=models.URLField(default='', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrap.Categories', verbose_name='категория'),
        ),
    ]
